### PR TITLE
Update matreshka-array.js

### PR DESCRIPTION
**Pull request by Rendol**
For move object from array to array, if use splice and push (save dom-element).

### CODE REVIEW

**Comment by Rendol** [comment]
Откомментировал как смог =) Приношу извинения за свои знания английского.
Изменение касается случая, когда необходимо переместить объект их одного массива в другой. При этом матрешка создавала новый dom-элемент, что плохо, т.к. все привязки придется делать заново. Сейчас dom-элемент перемещается вслед за объектом, но я не уверен, что учел все заложенные случаи использования bound. Прошу поправить меня, если что не так.

**Comment by finom** [comment]
Hi @Rendol!
Thanks for your contribution. I'd like to keep issue tracker for this repo English-speaking even though I'm not good in English as well :) 
Please, let's make comments in Russian at this repo: https://github.com/matreshkajs-ru/matreshkajs-ru.github.io even for pull requests.
(I know it might sound weird)

The use-case you've provided sounds good. But the idea is, an object can be contained in a few collections. For example: music search + your playlist. They both can contain same track object. So when you listen to a track from search collection a progress bar updates in your playlist as well. Bound nodes could be different (``itemRenderer`` for both collections are not the same). At this case you may need to use ``bindRenderedAsSandbox: false`` (look at [itemRenderer doc](http://matreshka.io/#Matreshka.Array-itemRenderer))

Your idea makes sense as well. But it breaks the logic described above.I think we might need something like "moveSandbox" option if you need to move a object to another collection including its sandbox.

```js
array.push_( item, { moveSandbox: true })
```

I need to think a while.

What do you think?
(If you need to speak in Russian, please create an issue in repo above)

Thank you!

**Comment by finom** [comment]
I'm going to push the latest fix soon. Thank you!

P. S. I've found another bug-feature (not sure how can I call it :)). When you push same object to an array twice or more, it doesn't render another HTML nodes.

**Comment by finom** [comment]
@Rendol look at develop branch. I'm closing this pull request.

```js
array.push_( item, { moveSandbox: true })
```
Thanks again

**Pull request closed without merging**
